CREATE DATABASE IF NOT EXISTS prim
CHARACTER SET utf8 COLLATE utf8_unicode_ci;
SET NAMES utf8;
USE prim;
CREATE TABLE Student (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  name tinytext NOT NULL,
  age int(11) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE Test(
  tid int(10) UNSIGNED AUTO_INCREMENT NOT NULL,
  tname text(100) NOT NULL, 
  PRIMARY KEY(tid));

CREATE TABLE Statistics(
  stid int(10) UNSIGNED AUTO_INCREMENT NOT NULL,
  id int(10) UNSIGNED NOT NULL, 
  tid int(10) UNSIGNED NOT NULL, 
  PRIMARY KEY(stid), 
  FOREIGN KEY(id) REFERENCES Student(id) ON DELETE CASCADE, 
  FOREIGN KEY(tid) REFERENCES Test(tid) ON DELETE CASCADE
  );


